DIR = '/content/' # work directory
PATH_TEST_DIR = DIR + 'test/'
PATH_TEST_LABELS =  DIR + 'test.tsv'
PATH_TRAIN_DIR =  DIR + 'train/'
PATH_TRAIN_LABELS =  DIR + 'train.tsv'
PREDICT_PATH = DIR + 'test/'
CHECKPOINTS_PATH = DIR
FROM_CHECKPOINT_PATH = None # if not None then training start with this checkpoint
WEIGHTS_PATH = None
PATH_TEST_RESULTS = DIR + '/test_result.tsv'
TRAIN_LOG = DIR + 'train_log.tsv'
