DIR = '/content/' # work directory
PATH_TEST_DIR = DIR+'test/'
PATH_TEST_LABELS =  DIR+'test.tsv'
PATH_TRAIN_DIR =  DIR+'train/'
PATH_TRAIN_LABELS =  DIR+'train.tsv'
PREDICT_PATH = "/content/test/"
CHECKPOINT_PATH = DIR
WEIGHTS_PATH = "/content/checkpoint_131.pt"
PATH_TEST_RESULTS = DIR+'/test_result.tsv'
TRAIN_LOG = DIR+'train_log.tsv'
